### ISSUE TITLE
Request for Reverse Engineering: PSU 1.8 Amp for Apple Lisa

### ISSUE THREAD

**Issue by mvwijland** [alexthecat123/Lisa-PCBs#1]
First and foremost, I'd like to express my admiration for the incredible work you've done on reverse engineering the Lisa PCBs. It's truly a remarkable contribution to the community and a testament to your skills and dedication.

I noticed that the power supply unit (PSU 1.8 Amp) for the Apple Lisa hasn't been covered (yet). I understand that reverse engineering is a complex and time-consuming process, but I was wondering if you might consider taking on this component in the future?

Most of the Lisa's have poor PSU, not only blowing out caps. An alternative PSU for the Lisa would benefit many people. 

Of course, I understand if you have other priorities or if this isn't something you're interested in tackling right now. Either way, I wanted to extend my gratitude for the work you've already done and express my hope for the possibility of a PSU. 

Keep up the fantastic work!

**Comment by alexthecat123** [comment]
Hi there!

Thanks for the kind words about my reverse-engineering efforts; it really means a lot! I'm just really glad that these boards are helping people bring their Lisas back to life!

It would be cool to make an exact replica of the 1.8A power supply, but unfortunately there are a few components in it (like the transformer) that are pretty much unobtanium (or at least pretty expensive) today. So that's why I haven't ever thought about doing the PSU. The good news is that my friend Will (AKA warmech) already made a Lisa PSU replacement that uses a modern pico ATX supply and some other components to replicate the functionality of the original supply. I've built a couple of them and they work really well, so that's what I would recommend if you're planning on replacing a power supply. You can find more info about Will's supply [here](https://github.com/warmech/lisa-hardware/tree/main/LisATX%20-%20Pico%20ATX%20PSU%20Replacement)! 

Let me know if you have any other questions!

**Comment by mvwijland** [comment]
Yes, these boards are more then important for many. 

Ah, didn't know about the _unobtanium_ ;) But the alternative is great news. You should see me smiling here, really great to hear. Have been search all the fora, but only now started looking in Github. Many great projects going on. Thank you for this nugget of gold.

Kind regards, Maurits

**Comment by alexthecat123** [comment]
Good luck with your Lisa adventures and I hope that Will's PSU replacement works for you!

Alex
